name:                RAScal-hs
version:             0.1.0.0
github:              "stschiff/RAScal-hs"
license:             BSD3
author:              "Stephan Schiffels"
maintainer:          "stephan_schiffels@eva.mpg.de"
copyright:           "2021 Stephan Schiffels"

extra-source-files:
- README.md
- ChangeLog.md

description:         A tool to compute Rare allele sharing statistics for ancient DNA datasets

dependencies:
- base >= 4.7 && < 5

executables:
  rascal:
    main:                Main.hs
    source-dirs:         src
    other-modules:       Paths_RAScal_hs
    dependencies:
    - poseidon-hs
    - optparse-applicative
    - parsec
    - sequence-formats
    - bytestring
    - aeson
    - yaml
    - text
